### ISSUE TITLE
Upgrade to Flowershow v2 and re-deploy at ecosystem.lifeitself.org

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#101]
## Acceptance

- [x] Running on latest Flowershow **✅2023-11-16**
- [x] Deployed at https://ecosystem.lifeitself.org **✅2023-11-19 FIXED ~~deployed but dns does not yet seem working for ecosystem~~**

## Tasks

- [x] Overwrite existing with new Flowershow
- [x] Convert index to a page as use custom React components
- [x] Convert any other pages like this **only `index.md` and `vis.md`**
- [x] Fix up profiles section - see screenshot below for issue **✅2023-11-19 FIXED. See 27475b954ddc8e40a0b90465a1cfa9b226a8d153**
- [x] Successful build on cloudflare pages **✅2023-11-19 all working - see https://36b26cb4.ecosystem-7yh.pages.dev** 
- [x] Deploy at ecosystem.lifeitself.org **✅2023-11-19**
- [x] Copy over tweaked hero (with typed functionality)  **✅2023-11-19**
- [x] Fixup title and description (change from polycrisis response mapping) **✅2023-11-19**

Bonus

- [ ] Make notes about improvements to Flowershow template and upgrade experience

### Profile page layout

![image](https://github.com/life-itself/ecosystem/assets/180658/5273920b-e439-4d49-9c80-4f6b351843ed)

## Notes re Flowershow template

- should we host all the commonly used images like logos somewhere and hardlink to them in all the apps (that currently have their own copies of these images)?
- removing 
- Why .gitattributes
- Why .prettierrc
- Why CHANGELOG.md
- etc

other stuff

- How do we get rid of puppeteer (e.g. conditional install of remark plugins)
- How do we make more stuff "optional" or plugins

**Comment by olayway** [comment]
@rufuspollock the site builds correctly now. Some of the md files were causing errors though so I moved them out of the /content folder to the temporary /tbd folder. What are the issues with these files?
1. All the ones moved out of /profiles have totally different frontmatter, e.g.:
```
---
Date last modified: 
Contributors: Matthew McCarthy
Date created: 2023-11-16
Name: The center for process studies
URL: https://ctr4process.org/
Main City: Portland
Main Country: United States
Operating Region: Global Network
Sectors: Education and Learning
Activities: Research
Date Founded: "2000"
Team size: 
project: cohere+
---
```
Not only didn't it match the one described in contentlayer.config file for Profile document type, but also field names include spaces which is causing errors.

2. Some of them include text in unescaped `{}`, which next-mdx-remote treats as js expressions. E.g. 

Pathways to Peace.md
```
{include or edit the following sections as appropriate/relevant}
```

**Comment by olayway** [comment]
@rufuspollock I've also managed to create a simple `MdxComponent` that you can use to wrap a md string and it will render it just as the `MdxPage` component. Example:

```jsx
<MdxComponent>
    This visualization maps organizations based on their approach to social change. There are three broad categories of approach: inner, cultural and systems oriented. [Read more about the visualization.](/vis)
</MdxComponent>
```

For multiline md strings they need to be wrapped in `{``}` so that whitespaces are taken into account.

```jsx
<MdxComponent>
    {`
# Overview of the Ecosystem

We sense that a new ecosystem, or ecosystem of ecosystems, is emerging. A growing number of people, organizations ...

## What is Novel in the Approach to Social Change?

The defining feature of this ecosystem is its **_novel_** **approach to social change**. Specifically, the combination of being paradigmatic, integrated, and pragmatic. We emphasize that it is the combination of all three that is important and distinctive.
    `}
</MdxComponent>
```

**Comment by olayway** [comment]
@rufuspollock let me know if I should work on it further, until it looks good and is ready to publish, or should I leave it for now

**Comment by rufuspollock** [comment]
@olayway this is cool - for MDXComponent i really want to be able to import by a file name (??)

**Comment by rufuspollock** [comment]
Close to being fixed. Just need to sort the profiles a bit.

**Comment by rufuspollock** [comment]
FIXED. All done. See above in acceptance etc.
