### ISSUE TITLE
Putting the cohere+ orgs onto the LI Ecosystem site 

### ISSUE THREAD

**Issue by matthewmccarthy11** [life-itself/ecosystem#139]
Although they build successfully through GitHub, it is difficult to find the cohere+ orgs on the ecosystem site, and they seemingly do not appear on the site. None of the headings available (about, contribute, glossary, report, contact, a project of LI and collaborators) or the hyperlinks within them provide a way to access these new orgs. 

## Acceptance 

- [x] A solution to (and understanding of) how we want the cohere+ orgs to appear on the LI Ecosystem website
- [x] Have at least 30 orgs on the site **✅2023-12-12 i believe as of now - in the tbd folder**

## Tasks 

- [x] Figure out the current location of the orgs in the 'tbd folder' on the ecosystem site (or if they don't appear)
- [ ] Discuss on Wednesday Nov 29th how we want the cohere+ orgs to look on the LI ecosystem site 
- [ ] Figure out a plan of work for how we want all orgs to pop up

**Comment by rufuspollock** [comment]
@matthewmccarthy11 wrote

> Hypothesis: based on the way the site builds, the organizations in the 'tbd' folder don't appear on the website, it is only orgs in the 'profiles folder', which appear.

@matthewmccarthy11 good you have a hypothesis. what evidence do you have for or against your hypothesis. e.g. if profiles files show up at X url where would tbd profiles show up? Do they show up there or not? Can you provide two examples to demonstrate your hypothesis ...

**Comment by matthewmccarthy11** [comment]
Hypothesis: based on the way the site builds, the organizations in the 'tbd' folder don't appear on the website, it is only orgs in the 'profiles folder', which appear. The organizations that do show up on the website appear the following way in the url: ecoystem.lifeitself.org/profiles/nameofprofile- for example, ecosysytem.lifeitself.org/profiles/enspiral. This is similar to how they are organized in the ecosystem repo- since they are in the 'profiles' folder and the sheet dedicated for each org has its name. 

This url format was tried for the new profiles: taking the ecoystem.lifeitself.org/foldername/sheetname- for example ecosystem.lifeitself.org/tbd/catalist. However, it did not work, and so if the profiles do show up in the ecosystem site it doesn't follow the same format.

**Comment by rufuspollock** [comment]
> This url format was tried for the new profiles: taking the ecoystem.lifeitself.org/foldername/sheetname- for example ecosystem.lifeitself.org/tbd/catalist. However, it did not work, and so if the profiles do show up in the ecosystem site it doesn't follow the same format.

We discussed on call that we needed to respect case. Matthew said he was doing that and it turned out he was mis-spelling Catalist as Catlist: https://ecosystem.lifeitself.org/tbd/Catlist

And then concluding from a sample size of one that it didn't work.

**Comment by rufuspollock** [comment]
FiXED. Closing as i believe both acceptance are met for now.
