### ISSUE TITLE
Prep for visualisation design meeting

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#151]
## Tasks

- [x] background on project generally **✅2023-11-30 see https://ecosystem.lifeitself.org/design**
- [x] background on eu project: https://lifeitself.org/blog/2023/08/30/cohere-erasmus-mapping-announce
- [x] specific goals in relevant area
- [x] existing tasks / issues to review **🚧2023-11-30  see https://github.com/orgs/life-itself/projects/6/views/4 plus some other items**

## Notes from Vis and UX meeting 2023-12-01

Present: Matt, Rufus, Catherine

- [x] 🧘 Meditation
- [x] 👋 Check-in
- [x] 🌥️ Context https://ecosystem.lifeitself.org/design
- [ ] Current intention of this phase II: provide more/better ways to understand this ecosystem and its relational to broader social change ecosystem. This work could take many forms e.g.
  - [ ] Visualizations - see past research https://github.com/life-itself/ecosystem/issues/4 and current list
    - [ ] "map" of concepts
    - [ ] "map" of orgs 
  - [ ] Written analysis
  - [ ] Collecting novel data e.g. text collection to do topic analysis or concept clustering
  - [ ] Comment: ultimately probably two needs
    - [ ] a marketing need for one compelling visualization ("looks cool" or "conveys an essential point")
    - [ ] broader analysis (visual or not) to identify interesting aspects of this
      - [ ] "State of Sensemaking" like State of JS
- [ ] AOB
  - [ ] Cohere+ Visualisations Design Brainstorm: https://app.excalidraw.com/l/9u8crB2ZmUo/At9xepR5sQS
- [ ] Next steps
  - [ ] Brainstorming phase
  - [x] Next meeting

### Rufus outflow

- a simple effort to collect language and visuals (ie. images/screenshots) could be a simple start - do a wordcloud or topicmaps ...
- medium-term: having regular snapshots / surveys ...
- Here's a crude "map" of sub-tribes that got traction https://twitter.com/rufuspollock/status/1501160815277318146

###  Matt Notes and Questions

- [ ] What is purpose of design document for ...
- [ ] Memetic tribes - https://docs.google.com/spreadsheets/d/11Ov1Y1xM-LCeYSSBYZ7yPXJah2ldgFX4oIlDtdd7-Qw/edit#gid=0
- [ ] Nadia Asparouhova - https://nadia.xyz/mapping-digital-worlds Nadia is more of a writer, conceptual writing format of sense-making, less visual
- [ ] https://nadia.xyz/climate-tribes
- [ ] https://ich.unesco.org/dive/constellation/
- [x] What is the openness to do different things? **Very open to whatever delivers sensemaking**
  - [x] How much do you want to develop on top of phase I vs figuring it out newly ... **Ans: we are very open to new**
- [x] What is timeline of project? **At least ~20d for Matt. Though can be less and possibly more.**

**Comment by catherinet1** [comment]
@rufuspollock I migrated today's meeting agenda and notes from hackmd to this issue.

**Comment by rufuspollock** [comment]
FIXED. This is complete.
