### ISSUE TITLE
Add Erasmus+ logo to Cohere+ related blog posts

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#166]
## Acceptance

- [x] All pages or blog posts on the LI website that mention Cohere+ project contain the Erasmus+ logo

This is requirement of the funding.

## Tasks

- [x] Find and download Erasmus+ logo (e.g. look for logo that partners have used when communicating about the project)
- [x] Add to https://lifeitself.org/blog/2023/08/30/cohere-erasmus-mapping-announce
- [x] Add to https://lifeitself.org/blog/2023/08/30/cohere-mapping-who-to-include

**Comment by matthewmccarthy11** [comment]
FIXED. Both blog posts now have the 'cohere plus project' logo along with the funded by eu sticker. 
https://39dba711.lifeitself-org.pages.dev/blog/2023/08/30/cohere-mapping-who-to-include
https://39dba711.lifeitself-org.pages.dev/blog/2023/08/30/cohere-erasmus-mapping-announce

**Comment by catherinet1** [comment]
Hi @matthewmccarthy11 I don't see the newly added images when I check the two blog posts on the website. Could you double check and troubleshoot, please? 🙏 (i also can't follow the two links pasted in the above comment, perhaps because they are build previews or something as opposed to live links on the website?)

**Comment by catherinet1** [comment]
FIXED. Both blog posts contain EU logo.
