### ISSUE TITLE
Processed backlog of third-party suggestions/submissions in google form as of 2023-12-06

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#170]
Processed backlog of third-party suggestions/submissions in google form as of 2023-12-06 (all submissions are from 2022 and before).

S: We have some old submissions (~22) from 2022 and before in the google form system (which we will deprecate) which have not been processed. We want to process these submissions.

## Acceptance

- [x] Reviewed all submissions and decided if they should be added or not ✅ **12/12/2023 there are 4 organizations which might be added to cohere+, and one to the ecosystem, as outlined in this sheet: https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=1603099986**
- [x] Make the additions where relevant
- [x] Notify all people who contacted us saying they are processed (and e.g. we'd love further contributions and suggestions - and sorry for the delay!)

## Tasks

- [x] Process existing submissions (22 in there) https://docs.google.com/forms/d/1cv7qMHFuDNp7Or7I6o7NRvnMYZ2TeOGAxMdV_mDdxdY/edit#responses
  - [x] First pass @matthewmccarthy11 **4 marked as to include in COhere+, 1 marked as to include in ecosystem but not Cohere+, 3 marked as Maybe**
  - [x] @elisapaka review 3 maybes against Cohere+ inclusion criteria **Reviewed and have added comments in the spreadsheet (2022 Google Form Submissions Tab)**
  - [x] Move Ys to Cohere+ DB index
- [x] Remove link to this form from website
- [x] Mark google form as deprecated in drive
- [x] Make the additions where relevant @matthewmccarthy11 
- [x] Notify all people who contacted us saying they are processed (and e.g. we'd love further contributions and suggestions - and sorry for the delay!) and cc labs@lifeitself.org @matthewmccarthy11

**Comment by rufuspollock** [comment]
@matthewmccarthy11 can you update the source spreadsheet (from google form) with info about whether in ecosystem or not and whether already in cohere+ e.g. a column for each. Plus a recommendation for includees and a notes column briefly saying why. (and please merge this info into the description of the issue - and you can transfer your notes from the old issue for this)

**Comment by catherinet1** [comment]
@matthewmccarthy11 there is a google sheet linked above which seems to be created on your personal drive (i didn't have access) instead of shared drive. flagging as i have noticed this a few times 

https://docs.google.com/spreadsheets/d/1oyzdGTfQ0lI5OfZqd5MUKzJbTSH4i8gbD1lMyrKK8XE/edit#gid=0

**Comment by catherinet1** [comment]
@elisapaka cc @matthewmccarthy11 p.s. i migrated the Google Form submissions processing into a tab called 2022 Google Form Submissions in our master Cohere+ Database spreadsheet https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=1603099986 so that we have all our org processing in one place (easier to find etc.). please use the Cohere+ database spreadsheet instead of the one now marked [DEP].

**Comment by catherinet1** [comment]
updated tasks in issue

**Comment by rufuspollock** [comment]
@catherinet1 i'd also update the description of issue with correct links now ...

**Comment by elisapaka** [comment]
@matthewmccarthy11 @catherinet1 I've reviewed the three orgs and have added comments in the relevant tab of the Cohere+ Database. Would be good to discuss these, or get your written feedback.

**Comment by matthewmccarthy11** [comment]
I think it makes sense to pass on those, since they are not as active anymore. But I'm still not sure about intentional society, I think @catherinet1 can decide on that one.

**Comment by catherinet1** [comment]
Thanks @elisapaka and @matthewmccarthy11. Let's put them all as No. I have updated the spreadsheet, also adding a comment to Intentional Society.

**Comment by catherinet1** [comment]
@matthewmccarthy11 is this issue now complete?

**Comment by matthewmccarthy11** [comment]
FIXED. All of the existing submissions have been tracked and put into the cohere database. Additionally, all of the people who submitted an organization have been emailed.

**Comment by rufuspollock** [comment]
@matthewmccarthy11 this issue is about more than just putting in the cohere database - this would be about add the profiles to the site.

Has that been done? (cf the one response you got from someone who asked that).

We want to use this as a positive opportunity to engage with people (e.g. "hi, we've got it up here - here's a blurb for sharing about it if you would like 😉 and if you'd like to get involved further in the project let us know!").. That is stronger if we have *actually published the thing* (if it is appropriate).
