### ISSUE TITLE
Fixing Headings on the Ecosystem Website 

### ISSUE THREAD

**Issue by matthewmccarthy11** [life-itself/ecosystem#177]
We want to make sure that the headings look appropriate on the website. 

## Acceptance 

- [x] All of the organizations have proper heading sizes **i.e. Highest heading level in the profile body is ## and profile starts immediately with description without an 'About' heading**

## Tasks 

- [x] Take out the 'about' section  in the template
- [x] Make the headings ## instead of # in the template
- [x] Update existing orgs the ecosystem repo so that they have this heading format **All orgs in the ecosystem repo in tbd folder were updated (?)**

**Comment by catherinet1** [comment]
Hi @matthewmccarthy11 could you add a little more detail to the issue update, so that it's easy for us to understand at a glance what the current status is if we want to refer back to this later and e.g. confirm what the correct heading formatting is?

For now, I put in what I imagine the more detailed update is in two comments in bold. Can you check whether that is correct and if so, close this issue (or make any necessary edits and then close) 🙏

**Comment by catherinet1** [comment]
Hi @matthewmccarthy11 i just noticed that the template doesn't seem to be updated -- see https://github.com/life-itself/ecosystem/blob/main/content/templates/profile.md.

Did you push that change?

**Comment by matthewmccarthy11** [comment]
FIXED. All headings are proper size, no longer contain the 'about' section

**Comment by catherinet1** [comment]
> FIXED. All headings are proper size, no longer contain the 'about' section

And is the template updated too, @matthewmccarthy11 ?? otherwise any new profiles we create will not have the correct heading formatting

**Comment by catherinet1** [comment]
I did not see the heading changes reflected in template, i.e. headings changed from h1 to h2. I have now done this.

**Comment by catherinet1** [comment]
FIXED. Headings were updated for all orgs in the ecosystem repo tbd folder and headings format was updated in the template.
