### ISSUE TITLE
Sharing tribes/centres brainstorm on twitter from 2023-12-09

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#183]
## Acceptance

- [x] Tribes/centres diagram tweeted **Tweeted on LI and Catherine personal Twitter**

## Tasks

- [x] [Catherine] Tweet tribes/centres diagram with short blurb
  - [x] Get image ![Screenshot 2023-12-13 at 15 12 22](https://github.com/life-itself/ecosystem/assets/97066487/a7baffbf-e4e4-45a2-8eaf-3ba96226dffd)
  - [x] Draft blurb 
  - [x] Post

**Comment by catherinet1** [comment]
FIXED. Shared on LI and Catherine twitter.
