### ISSUE TITLE
Blog post or discussion thread posted re tribes/centres brainstorm (and related efforts)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#185]
## Acceptance

- [ ] Find examples of "tribes" in our area
- [x] Blog post or discussion thread re tribes/centres brainstorm (and related efforts) **Discussion thread here: https://github.com/orgs/life-itself/discussions/969. A few things to add, flagged in the post, e.g. brief notes on each of the efforts**

## Tasks

- [x] Find examples of efforts to map "tribes" in our area
- [ ] Write up brief notes on these in a discussion thread, including e.g. **Discussion post here: https://github.com/orgs/life-itself/discussions/969**
  - [ ] Why
  - [x] Examples listed below
- [ ] Blog post
  - [ ] Review recording of 2023-12-21 Meeting (see notes below for timestamp) and incorporate Catherine and Matt discussion about tribe mapping 

### Notes from 2023-12-21 Meeting

- [ ] Matt's and Catherine's discussion about tribe mapping
  - [ ] At ~ 1101 (probably 20m in) Catherine explains why tribe-mapping could be useful. 🚩
  - [ ] If we can't see our differences we can't work constructively with them
  - [ ] Maybe use an alternative word to 'tribe', e.g. 'interest' but something stronger... affinity?

### "Tribe" mapping efforts

- Memetic tribes - https://docs.google.com/spreadsheets/d/11Ov1Y1xM-LCeYSSBYZ7yPXJah2ldgFX4oIlDtdd7-Qw/edit#gid=0
- Nadia Asparouhova - https://nadia.xyz/mapping-digital-worlds
  - https://nadia.xyz/climate-tribes
- Twelve Tribes of Transformation
- Brandon Norgaard Approaches to the Metacrisis
- WP4 spreadsheet?

**Comment by catherinet1** [comment]
I added 5 examples of related efforts to map "tribes" in Analysis section above

**Comment by catherinet1** [comment]
DUPLICATE. Replaced by https://github.com/life-itself/ecosystem/issues/237.
