### ISSUE TITLE
Process material from mapping/visualisation brainstorming meetings

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#193]
cf https://github.com/orgs/life-itself/discussions/958

## Acceptance

- [x] All actionable items processed into issues
- [x] Location identified for storing reference material
  - [x] Reference material (non-actionable items) processed here

## Tasks

- [x] Identify location for storing reference material **Either directly into a relevant issue if it is directly supporting an issue and/or into a more stable location, e.g. page in wiki. Or a blog post (or discussion thread). (+ see analysis below)**
- [x] Process 1st meeting: https://github.com/life-itself/ecosystem/issues/151 **Reviewed all meeting notes and processed into issues, i.e. organising notes into Analysis section of #184 and processing related efforts below.**
  - [x] Add these related efforts to https://ecosystem.lifeitself.org/related-efforts: **For now just pasted quickly on there**
    - [x] Memetic tribes - https://docs.google.com/spreadsheets/d/11Ov1Y1xM-LCeYSSBYZ7yPXJah2ldgFX4oIlDtdd7-Qw/edit#gid=0
    - [x] Nadia Asparouhova - https://nadia.xyz/mapping-digital-worlds Nadia is more of a writer, conceptual writing format of sense-making, less visual
    - [x] https://nadia.xyz/climate-tribes
    - [x] https://ich.unesco.org/dive/constellation/
- [x] Process 2nd meeting: https://github.com/life-itself/ecosystem/issues/180
  - [x] Boot a page called e.g. ecosystem.lifeitself.org/sensemaking **Here: https://ecosystem.lifeitself.org/sensemaking**
  - [x] Gather reference materials such as visualisation brainstorms here (and links to relevant blog posts or discussion threads) **Organised relevant meeting notes under relevant headings on above page**

### Location for storing reference material
Either directly into a relevant issue if it is directly supporting an issue and/or into a more stable location, e.g. page in wiki. Or a blog post (or discussion thread).
- Background/context on the Ecosystem Mapping project in general: https://ecosystem.lifeitself.org/design
- Background on the EU-funded Cohere+ project (a sub-iteration of LI's broader Ecosystem Mapping): https://lifeitself.org/blog/2023/08/30/cohere-erasmus-mapping-announce
- Related efforts: https://ecosystem.lifeitself.org/related-efforts

**Comment by catherinet1** [comment]
FIXED. All actionable items processed into issues and all reference material processed into issues as supporting material and/or onto relevant wiki pages e.g. /related-efforts and /sensemaking (new page).

**Comment by catherinet1** [comment]
cc @rufuspollock p.s. I booted new page to capture a consolidated brainstorm that we can build on re our sensemaking and visualisation brainstorming work: https://ecosystem.lifeitself.org/sensemaking
