### ISSUE TITLE
[epic] Previous work/Literature Review of Ecosystem Mapping

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#212]
## Acceptance

- [ ] Published 1-2 blog posts (or do live chat and then post that with a write-up of it, or ... )
   - [ ] The visualization inspirations #184 
   - [ ] Approaches to sensemaking and some previous inspiration (either in our area or outside) e.g. memetic tribes, liminal web piece, even our own sensemaking efforts etc #185

**Comment by catherinet1** [comment]
DUPLICATE. Replaced by https://github.com/life-itself/ecosystem/issues/237.
