### ISSUE TITLE
Sketch and share 2D maps identifying landmarks and regions

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#213]
## Acceptance

- [ ] Sketched 5-10 (?) 2D maps, starting with landmarks we know e.g. people, thinkers, podcasts, blogs and seeking to identify "regions" (emergently potentially)
- [ ] Map sketches shared on Twitter, asking for feedback
- [ ] [BONUS?] Series of map sketches published in one place (e.g. blog post), inc. any notable feedback, and linked on ecosystem.lifeitself.org/sensemaking

## Tasks

- [ ] Sketch 2D maps identifying key landmarks and regions, inspired by: https://slatestarcodex.com/2020/02/02/map-of-effective-altruism/
- [ ]  Share on Twitter and ask for feedback

## Notes

Suggestions from Rufus:
- Ship one map sketch and share a week (or a day)
- Flag it is incomplete/a sketch -- knowing that it's going to be "wrong"/incomplete gives us freedom
- Stick with the constraint of the 2D geographical map, can represent landmarks and group them into areas - https://slatestarcodex.com/2020/02/02/map-of-effective-altruism/
- Use this as an opportunity to cycle through different possibilities, e.g. 
  - different maps might feature different 'nodes' out of the ones we discussed (nodes might be people, thinkers, blogs, etc.)
  - different maps might focus on different sub-areas of the territory, e.g. engaged spirituality, or eco-spirituality, or metamodernists etc
- Each map can show several things e.g. the major regions and the "hubs/campfires" etc. of that (sub-)territory.

**Comment by catherinet1** [comment]
Created this issue and assigned to @mattosborn based on @rufuspollock suggestions from Visualisation Sync Meeting 21-12-2023. Full meeting notes are here: https://github.com/life-itself/ecosystem/issues/208.

**Comment by rufuspollock** [comment]
WONTFIX. Didn't happen at the time. sort of merged with #243
