### ISSUE TITLE
Next actions from Visualisation Sync Meeting 2023-12-21

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#216]
Full meeting notes are logged in #208.
 
## Tasks

- [x] Catherine add meta tribes (https://www.joelightfoot.org/post/the-liminal-web-mapping-an-emergent-subculture-of-sensemakers-meta-theorists-systems-poets) to tribe/centre mapping efforts (NB: this came out at same time as our original mapping - and we talked with Joe about it) **Added to: https://github.com/orgs/life-itself/discussions/969**
- [x] Matt share with us the memetic tribes essay **Shared PDF in https://github.com/orgs/life-itself/discussions/969**
- [ ] Matt post notes on nodes/relations as a discussion thread @mattosborn 
- [x] Catherine process today's meeting notes https://github.com/life-itself/ecosystem/issues/208 **Processed into relevant issues and updated ecosystem.lifeitself.org/sensemaking**
- [x] Schedule a sprint (e.g. w/c 29 Jan) @catherinet1 **Sprint scheduled for w/b 13/2**
- [x] Elisa read ecosystem.lifeitself.org/sensemaking @elisapaka

**Comment by catherinet1** [comment]
Hi @mattosborn and @elisapaka please can you update your respective actions above when done?
Whoever of us completes the last action on here, please close this issues as FIXED.

**Comment by rufuspollock** [comment]
FIXED. All done pretty much.
