### ISSUE TITLE
Complete frontmatter for 20 profiles

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#217]
## Acceptance

- [x] 20 new profiles have frontmatter complete **21 profiles have complete frontmatter, 7 of these also have profiles complete. Most of these were not brand new but were editing/adding to existing work.**
- [x] Status updated in Index tab of https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=568491195

## Tasks

- [x] Elisa tidy up Index tab and research status column **P.s. Catherine created new column called 'research status' with 2 dropdown categories explained in 'notes' section below.**
- [x] Do 20 orgs **21 done. Most of these were not brand new but were editing/adding to existing work.**

### Research status

1 (basic) means:
- frontmatter fields complete (where data found)
- description pasted in
- image (normally screenshot of homepage) both in frontmatter and pasted in

2 (complete) means:
- relevant content under all template headings
- in good, shareable format

**Comment by catherinet1** [comment]
2024-02-09 update: Reviewed and updated 9 profiles and updated research status column in Index tab of spreadsheet: https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=568491195.
- 6 at Status 1 (frontmatter, description & image)
- 3 at Status 2 (complete profile)

**Comment by catherinet1** [comment]
2024-02-12 update: 
- Reviewed and updated 1 profile **status 2**
- 1 new profile **status 1**

**Comment by catherinet1** [comment]
Hi @elisapaka I'm going to close this issue and open a new one with a new goal for our org research this week. (I find it helpful for motivation + sense of accomplishment.)

**Comment by catherinet1** [comment]
FIXED. 
- 21 profiles have complete frontmatter, 7 of these also have profiles complete. Most of these were not brand new but were editing/adding to existing work. 
- Defined 2 levels of research status: 1 (basic) and 2 (complete) -- see notes above.
