### ISSUE TITLE
Shape Interactive Digital Map

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#230]
## Acceptance

- [ ] Shaped proposal for interactive digital map
- [ ] Feedback from Rufus

## Tasks

- [ ] Boot pitch in ecosystem repo
- [ ] Create issue tree
- [ ] Work through issue tree
- [ ] Draft pitch
