### ISSUE TITLE
2nd Renaissance Landing Page v0.1

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#236]
Part of: https://github.com/life-itself/ecosystem/issues/238

## Acceptance

- [x] Landing page is live on new domain (or ecosystem.lifeitself.org if we haven't chosen) **✅2024-03-20 live at https://secondrenaissance.net/new**

## Tasks

```[tasklist]
### Landing page
- [x] Draft landing page text
- [x] Design landing page
- [x] Technical setup of site
- [x] Fix links to intro and ecosystem page
```

```[tasklist]
### Deploy
- [x] Choose new domain name, 2ndrenaissance.org or secondrenaissance.net
- [x] Move ecosystem page to /ecosystem and new home page to root
```

## Posts stuff

# 2024-03-19 - Content links/info

### Overview of ecosystem names

Title: Many names, one ecosystem?
URL: https://ecosystem.lifeitself.org/wiki
Description: An overview of the different names and terms that the Second Renaissance ecosystem is associated with
Type: wiki page

### Overview of related mapping efforts

Title: An Overview of Second Renaissance Ecosystem Mapping Efforts
URL: https://ecosystem.lifeitself.org/wiki/overview-mapping-efforts
Description: An overview of different efforts to map the Second Renaissance (or closely related) ecosystem(s)
Type: wiki page

### Emergent Power report

Title: Emergent Power: Key Challenges and Capacities for Change Agents of a Second Renaissance - a new report
URL: https://lifeitself.org/blog/emergent-power-report-2024
Description: A report on key challenges and capacities for change agents of a Second Renaissance
Type: blog post

### Second Renaissance Intro Course

Title: Second Renaissance Introductory Course
URL: https://lifeitself.org/second-renaissance
Description: A course introduction to the idea of the Second Renaissance, covering the idea of views and values as "foundations" of our societies, cultural paradigms and their role history, the birth and decay of modernity, and what comes next
Type: web page

### Joseph Henrich podcast

Title: Joseph Henrich and the Emergence of a (Rigorous) Culturology
URL: https://lifeitself.org/podcast/joseph-henrich-and-the-emergence-of-culturology
Description: A podcast episode where Rufus talks with Joseph Henrich about study of cultural evolution 
Type: podcast episode

### Sylvie talking about the 2R

Title: Are We Experiecing The Second Renaissance? with Sylvie Barbier
URL: https://lifeitself.org/blog/2023/05/19/sylvie-barbier-second-renaissance
Description: Video in which Sylvie shares about her upcoming book "Second Renaissance" and its connection to Life Itself's vision for a radically, wiser, weller world
Type: podcast episode

### Need in following format

```javascript
const posts = [
  {
    title: 'Boost your conversion rate',
    href: '#', // link to post
    description: 'Illo sint voluptas. Error voluptates culpa eligendi. Hic vel totam vitae illo. Non aliquid explicabo necessitatibus unde. Sed exercitationem placeat consectetur nulla deserunt vel. Iusto corrupti dicta.',
    imageUrl:
      'https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3603&q=80',
    date: '2020-03-16',
  },
  // More posts...
]
```

**Comment by rufuspollock** [comment]
FIXED. All core stuff done. Incomplete items moved to follow up in #258 (or dropped)

![image](https://github.com/life-itself/ecosystem/assets/180658/2a88120f-5d74-4826-8612-ba139fcb87a5)
