### ISSUE TITLE
Literature review: names and descriptions of the ecosystem

### ISSUE THREAD

**Issue by elisapaka** [life-itself/ecosystem#237]
Readable version of first literature review: existing names / related efforts

## Acceptance

- [ ] Directory / overview post of names for "this" ecosystem. NB: this can shade into related key concepts (e.g. is metacrisis a name for ecosystem or a key concept. Don't worry too much)
  - [ ] BONUS: not just a listing. We compare previous approaches and draw out key insights and disagreements we may have 
- [ ] Directory / overview of related mapping efforts
  - [ ] BONUS: what is/are our research question(s)? Hypotheses: e.g. What dimensions have others compared tribes against? What questions remain open? What is missing in terms of orgs/thinkers? Tribes vs sub-tribes (?)

## Tasks

*NB these will likely be part of the same blog post, but makes sense to split out in terms of tasks.*

### Ecosystem names

- [ ] Research
  - [ ] Find what we have already
  - [ ] List of names for the ecosystem
  - [ ] Inbox of materials that describe / explain / represent each of the names
- [ ] Analysis [BONUS]
  - [ ] Draw out key similarities and differences
- [ ] Write up
- [ ] Publish on new site

### Mapping / sensemaking efforts

- [ ] Research
  - [ ] Find what we have already
  - [ ] Inbox of other mapping / sensemaking efforts
- [ ] Analysis [BONUS]
  - [ ] Draw out 'definitions' of tribes/centres
  - [ ] Draw out key dimensions
  - [ ] Compare and synthesise
- [ ] Write up
- [ ] Publish on new site

**Comment by catherinet1** [comment]
FIXED. Review of names for ecosystem and efforts to map it are published here: https://ecosystem.lifeitself.org/overview. And shared in research community WA group, Twitter and LinkedIn.
