### ISSUE TITLE
[epic] 2nd Renaissance & Its Ecosystem Part I

### ISSUE THREAD

**Issue by elisapaka** [life-itself/ecosystem#238]
Implementation of 2409 2R Mapping and Sensemaking Pitch (Level 2) https://github.com/life-itself/comms/blob/main/pitch/2409%202R%20Mapping%20and%20Sensemaking.md

## Acceptance

```[tasklist]
### Scoped
- [ ] https://github.com/life-itself/ecosystem/issues/237
- [ ] https://github.com/life-itself/ecosystem/issues/239
- [ ] https://github.com/life-itself/ecosystem/issues/236
- [ ] https://github.com/life-itself/ecosystem/issues/242
- [ ] https://github.com/life-itself/ecosystem/issues/243
- [x] Inbox of materials **✅2024-03-18 see below**
- [x] Preliminary content in the wiki **✅2024-03-18 see section below. Have a start and this wasn't in the pitch so a start is enough for now**
- [ ] https://github.com/life-itself/ecosystem/issues/245
```

```[tasklist]
### Immediate fixes 2024-03-20
- [ ] 🔥 Edit "lit review" names page
- [ ] Edit "lit review" related efforts page
- [ ] Tidying up of other pages, e.g. check links etc.
```

## Items

```[tasklist]
### Prep inbox of materials
- [x] Create inbox **Created inbox in README**
- [x] Review blog content **Have scanned through blog posts from August 2021 until now and picked out content most relevant to 2R mapping and sensemaking and captured in README inbox.**
- [x] Identify ranking criteria for prioritizing e.g. quality, relevance, finished-ness
- [x] Rank items for inclusion in wiki and/or blogging and shortlist somewhere e.g. as items in wiki section 📆 @elisapaka (?) Catherine already did some of this while adding material to the README. **Added fire emojis next to priorities**
- [ ] BONUS: Review older blog posts(?)
```

```[tasklist]
### Preliminary content in wiki
- [x] Framing / Architecture **See Coggle: https://coggle.it/diagram/Ze8Y4aL0bmg_e6HG/t/- Not 100% polished i.e. wouldn't publish, but good enough for internal use for now**
- [x] Put up simple index page? **Index page stubbed: https://ecosystem.lifeitself.org/wiki**
- [x] Tidy wiki folder **ecosystem/content/wiki is now empty. There were a bunch of images in here --> moved to assets folder. Moved 2 files 'profiles-template' and 'topics-template' to templates folder**
- [x] Mapping Metamodern summaries **Added 8 summaries (on e.g. Zen, Permaculture, Psychotherapy etc. to wiki**
- [x] Ancestors page stubbed 📆 @elisapaka **Page stubbed here: https://ecosystem.lifeitself.org/wiki/ancestors**
- [x] Make sure all content from here is migrated to relevant literature review and then close https://github.com/orgs/life-itself/discussions/969
- [x] Meta-tribes page with content from Stoa folks **Page here: https://ecosystem.lifeitself.org/wiki/memetic-tribes**
- [x] Ever-green version of the names for the ecosystem list **✅ 2024-03-12 Done https://ecosystem.lifeitself.org/wiki/overview-ecosystem-names**
- [x] Previous/related efforts page **✅ 2024-03-12 Done https://ecosystem.lifeitself.org/wiki/overview-mapping-efforts**
- [x] Redirect for `/overview/` page that has move to /wiki/overview-ecosystem-names/ **✅2024-03-15 rufus fixed today**
- [x] Podcasts **✅2024-03-18 sort-of we have listed podcasts on people page of people listed from people section on front page**
```

```[tasklist]
### Unscoped
- [x] Sharing about the work produced in this iteration **✅2024-04-03 did this to some extent with limicon talks and some online posting. could do more.**
- [x] BONUS: Post/essay analysing some key thinkers/frameworks: Ken Wilber, John Vervaeke, Iain McGilchrist, Donna Haraway **✅2024-04-03 ❌**
- [x] BONUS: Short but reasonably polished "wiki" pages on key concepts e.g. integral, liminal web, metamodern, gameb (evolution of literature review) **✅2024-04-03 ❌ had these as part of names analysis but no separate pages for now**
- [x] BONUS: Why the term second renaissance **✅2024-04-03 ❌ did not get to this**
- [x] BONUS: [post/wiki] what is the meta-crisis": writing up our own explanations and work and referencing that of others ... **✅2024-04-03 ❌ did not get to this**
- [x] BONUS: "Literature review" is not just a listing: we analyse/compare previous approaches and draw out e.g. key insights, disagreements, things missing, open questions **✅2024-04-03 ❌ did not get to this**
```

```[tasklist]
### Sharing etc
- [x] Share ancestors wiki page with general chat ...
```

```[tasklist]
### Misc
- [x] Follow up with Brandon Norgaard. He emailed us back in 2021/2022 and we should ask him to participate / advise. **✅2024-03-12 Rufus emailed Brandon Norgaard**
- [x] Schedule meeting with Brandon **✅2024-03-20**
- [x] BONUS: follow up with Gaianet **✅2024-04-03 ❌ have chatted and someone pinged us but not done yet**
```

## Notes / questions

- [x] Where is this content/code located? **planning that we take over ecosystem repo (?)**
- [x] deploy at new url e.g. secondrenaissance.net (or 2ndrenaissance.org)? **✅2024-03-07 secondrenaissance.net**
- [x] What do we do with existing ecosystem content? **Bulk move to sub url e.g. /2021/ or similar, or even we can move to 2021.stateofemergence.org or something**
- [x] Do we have a second site or take over ecosystem.lifeitself.org?

**Comment by rufuspollock** [comment]
FIXED. All complete about 2w ago. have migrated remaining misc etc to #257
