### ISSUE TITLE
Publish intro/announcement to new 2R Mapping & Sensemaking work

### ISSUE THREAD

**Issue by elisapaka** [life-itself/ecosystem#239]
Part of: https://github.com/life-itself/ecosystem/issues/238

- May include wiki stubs for ideas etc

## Acceptance

- [x] Blog post published on site **Blog post containing 2R mapping and sensemaking work background (SCQH) and proposed upcoming work published here: https://lifeitself.org/blog/second-renaissance-mapping-and-sensemaking**

## Tasks

- [ ] Outline
  - [ ] SCQH (global version)
  - [ ] What is the Second Renaissance (v brief, e.g. 1 para, not detailed analysis/definition, more about framing what we're doing now and why)
    - [ ] Situation
    - [ ] Diagnosis
    - [ ] What is needed
  - [ ] Lack of consensus in the wider ecosystem (i.e. this is our perspective!)...
  - [ ] Announcement of new Second Renaissance website **different post**
- [ ] Write up 
- [ ] Publish

**Comment by catherinet1** [comment]
FIXED. Blog post announcing 2R mapping and sensemaking work background (based on SCQH) and proposed upcoming work published here: https://lifeitself.org/blog/second-renaissance-mapping-and-sensemaking.
