### ISSUE TITLE
[inbox] Things to post

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#248]
```[tasklist]
### Visualization ideas post
- [ ] Post visualization idea stuff as a blog post https://github.com/orgs/life-itself/discussions/1043
- [ ] ?? Also migrate https://github.com/orgs/life-itself/discussions/1043 to a wiki page e.g. `Visualization ideas` in the wiki so it can be updated over time
- [ ] Add to that the stuff in #208
- [ ] BONUS Add screen shots / example of the visualization we did in 2021
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
