### ISSUE TITLE
2020 ecosystem mapping report/landing page

### ISSUE THREAD

**Issue by catherinet1** [life-itself/ecosystem#250]
## Acceptance

- [x] Landing page live at `/ecosystem/state-of-sensemaking-2020` **Page complete and live here: https://secondrenaissance.net/ecosystem/state-of-sensemaking-2020**
  - [x] Introduction/Motivation 
  - [x] Report and Coggle map 
- [x] Contains PDF version of 2020 report

## Tasks

- [x] Introduction/Motivation
  - [x] Link/integrate https://lifeitself.org/blog/2020/08/27/ecosystem
- [x] Map and Report
  - [x] Migrate content from this page: https://github.com/life-itself/community/blob/main/content/state-of-sensemaking-2020.md
  - [x] then delete this page? 
  - [x] https://lifeitself.org/blog/2020/09/02/weve-published-our-ecosystem-snapshot-report

**Comment by catherinet1** [comment]
@rufuspollock does it make sense to delete this page? https://github.com/life-itself/community/blob/main/content/state-of-sensemaking-2020.md

**Comment by catherinet1** [comment]
FIXED. 2020 Ecosystem Mapping work synthesised into one landing page/report here: https://secondrenaissance.net/ecosystem/state-of-sensemaking-2020.
