### ISSUE TITLE
Visual Mapping for 2R Ecosystem Mapping and Sensemaking v0.2

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#263]
![image](https://github.com/life-itself/ecosystem/assets/180658/16940758-3867-4ae1-9ab8-fc979bae3c83)

## Tasks

```[tasklist]
### Tasks
- [ ] Second Renaissance ecosystem map (i.e. level 1 / 2)
- [ ] Polish broader ecosystem map
```

BONUS

- [ ] BONUS: Doing a nice version of Brandon Norgaard viz
- [ ] BONS Brainstorming more maps ...

# Pitch: "Pure" Mapping/Sensemaking re 2R v0.2

- **Appetite**: 5d

## Situation

- Mapping / Sensemaking work: describing the ecosystem, doing sensemaking ... so that ... others can use that to make sense of what is going on
- With mapping, we now know where we are roughly and it's ok mostly for now (i.e. this iteration).
- 3 levels:
  - Our definition (2R): sketched and overlaps with wider effort
  - Rosetta stone: have list of similar names. Could do more to flesh out. Bigger work (e.g. real analysis) is time consuming
  - Broader ecosystem: Matt's map. Again proper work is extensive.
- Always loads more we *can* do but not much that is urgent.
- Recording from 2024-03-15: https://drive.google.com/file/d/1m23g3STOyekq_gBAzs5TGSCld5hNEi7j/view
  - 20m in has 3 levels discussion

## Problem

- Don't have a nice map of the "second renaissance" which is what is most important
- Broader map is not yet polished (minor: and we don't have a name yet)

## Hypothesis

Focus on:

- Second Renaissance ecosystem map (i.e. level 1 / 2)
- Polish broader ecosystem map
- [ ] BONUS: Doing a nice version of Brandon Norgaard
- [ ] BONS Brainstorming more maps ...

**Comment by catherinet1** [comment]
2024-04-17 update: @elisapaka drafted a short framing for Matt's map work so far and it is published here atm (we are aware that the map is not for sharing yet): https://secondrenaissance.net/publications/map-paradigmatic-changemakers

**Comment by rufuspollock** [comment]
FIXED. We produced the following draft map at the end of this on 2024-04-18. There was still a discussion about whether this represented broad ecosystem (level 3) or rosetta stone (level 2). However, it was where we reached and now superseded by insight/clarity that we sort-of covering both in #302 

> Map of Paradigmatic Changemakers ecosystem
> 
> 🚩 Not yet for broader sharing please 😉
> 
> This is a "level 2" (broader ecosystem) map. This is ~ v0.4 and still more iterations to come. Welcome feedback of course.
> 
> Credit: almost entirely @⁨Matt Osborn⁩ who has been doing an incredible job.
> 
> Reiterate that any errors / omissions lie not with him but whole team 😉 (it is very hard to included everyhting that should be there!)

![image](https://github.com/life-itself/second-renaissance/assets/180658/38175013-d597-443c-9070-740c345a4523)
