### ISSUE TITLE
Curators Guide v0.1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#37]
Starting a curators / contributors guide.

When I am contributing to the database I want to know how to do that and especially what fields there are and what they mean so that i can be efficient and not have to ask lots of questions

When I have some organisations that I'd like to contribute to the database, I want to understand what the criteria for relevance and acceptance in the database are (e.g. do I need to be personally in contact with the organisation/how much vetting do I need to do or will someone else vet my contribution) so that I know whether it is worth my time to contribute my suggestions.

## Acceptance

* [x] `/curators/` exists on the website **DONE. https://ecosystem.lifeitself.us/curators**
* [ ] instructions re images **DONE? but may be out of date now ...**
* [ ] info on metadata fields e.g. embedding appropriately of the [schema spreadsheet](https://docs.google.com/spreadsheets/d/1sotA3Cm79B1te4ooMQvPk6OHdaxZwnDB2VRLtfQAuRE/edit#gid=106528583) **Have a link but no embedding atm**

## Tasks

* [x] Boot the page
* [x] Draft guide: **https://docs.google.com/document/d/1UhtUtFJPOD5UYz6aUpALHl0Y8yGPeEaviAgFbn5OUjw/edit#**
* [x] Finalize info on metadata fields **Org metadata tab of spreadsheet explains metadata fields**
* [x] https://github.com/life-itself/ecosystem/issues/61 
* [ ] Create obsidian template for a new profile

**Comment by rufuspollock** [comment]
@catherinet1 could we merge this with #77 (and how much of the old guide is still relevant?)

**Comment by catherinet1** [comment]
Reviewed this issue to see what to merge with #77 and added 1 task to https://github.com/life-itself/ecosystem/issues/77 to integrate anything useful from this curators guide.

**Comment by catherinet1** [comment]
WONTFIX. Site structure has been changed to markdown wiki-like structure and so this curators guide is largely irrelevant. 1 task added to new contributor workflow issue #77 to integrate anything useful from here.
