### ISSUE TITLE
Making best use of the offers to help

### ISSUE THREAD

**Issue by theo-cox** [life-itself/ecosystem#49]
We're getting a number of offers to support the project, and we don't yet have a concrete process for moving these forward or managing volunteers.

## Acceptance

- [ ] A pattern for responding to offers of support exists
- [ ] A backlog of taks suitable for volunteers exists
- [ ] We have a plan for engaging and managing volunteers

## Tasks

- [ ] Strategy meeting between @rufuspollock and @theo-cox held
- [ ] Tasks backlog created
- [ ] Creation volunteer engagement/management created
- [ ] Hack day planned and scheduled (??)

**Comment by rufuspollock** [comment]
FIXED / WONTFIX / DUPLICATE. Repo is now open and we have plan for contributor workflow #77. We won't be doing a hackday and atm we want to see what kind of people with what skills/interests want to engage before we do much more.
