### ISSUE TITLE
Integrate "meta" content e.g. job stories, why the project

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#51]
## Background

Currently have a bunch of "meta" content that is useful for people really working on the project (or those curious about the details of why and how). This is spread around in various places e.g. job stories, blog posts etc.

What is needed and who needs it?

* People actively contributing to the project often want some detail on *why* we are doing the project e.g. who is going to use it for what etc. ie. what are the *job stories*. They may also want documentation of design 
* People who are curious about background: want a why and maybe a timeline

## Acceptance

- [x] Materials below analysed for what is useful to include in integrated 'background' to and 'vision' for ecosystem mapping **✅2023-11-30 looked through it all**
- [x] Useful bits collated into one place, with links to further reading if necessary **✅2023-11-30 on https://ecosystem.lifeitself.org/design**
  - [x] Job story for what and why to publish - https://docs.google.com/document/d/1vWcBp9l40-KRDxRIhHSuFK0vP4B_zMzzZ1bcJL_eRJ0/edit# **✅2023-11-30 processed and extracted all relevant parts and deprecated section in gdoc**
  - [ ] Why / background e.g. A10 **🚧2023-11-30 need to add still**
  - [x] Timeline **✅2023-11-30 wrote a draft timeline**
  - [x] Roadmap **✅2023-11-30 https://github.com/orgs/life-itself/projects/6**
  - [x] Architecture **✅2023-11-30 added a section on this**
- [x] Shared/published somewhere, e.g. on relevant initiative page? **✅2023-11-30 https://ecosystem.lifeitself.org/design**

## Tasks

- [ ] Analyse below materials and flag what is useful to include **analysis is happening in this document here: https://docs.google.com/document/d/1xL8LWayhxCfHlJhl6TjzuzzQRAcw-MI7Fw6zDngjmlw/edit**

### What do i do atm to onboard someone

Gave them this set of links

* https://lifeitself.us/2021/12/09/mapping-for-emergence/ 
* [Job Stories and Design Document - Ecosystem Mapping (State of Sensemaking) - Gdoc](https://docs.google.com/document/d/1vWcBp9l40-KRDxRIhHSuFK0vP4B_zMzzZ1bcJL_eRJ0/edit#)
* [Project Summary: Ecosystem Mapping 2020 P2032 [A10] and key links therein](https://docs.google.com/document/d/1bRqgwP7iSXBvnqf4sMnPmJJkdKStuDCiUZAOoRPh9SQ/edit#)
* Read a bit of https://ecosystem.lifeitself.us/ and esp https://ecosystem.lifeitself.us/about and maybe a few profiles
* Then look at the task list and ecosystem planning board: https://github.com/life-itself/ecosystem/projects/1 

## Notes

* https://lifeitself.us/2021/12/09/mapping-for-emergence/ - this is a narrative version that combines a summary of both the state of the project and *why* we are doing it
  * NB: there is an internal gdoc there the why is more bullet pointed and simple and clearly separated. May be better for more "docs" type stuff
* Job stories doc: https://docs.google.com/document/d/1vWcBp9l40-KRDxRIhHSuFK0vP4B_zMzzZ1bcJL_eRJ0/edit#
* Architecture: Not much, a bit in the README

**Comment by catherinet1** [comment]
@rufuspollock - as part of capture and clarify existing mapping research design materials in Omega project kickoff phase, I have collated relevant material from this issue into this spreadsheet: https://docs.google.com/spreadsheets/d/1UUhaGaBZwbv2_ohxSLCOlCPDsRwZihRaJUd5OlpTjuQ/edit#gid=0 . I would say that could be enough to close this issue now -- what do you think ?

**Comment by rufuspollock** [comment]
@catherinet1 this actual task was more about providing context for ecosystem project so i don't think capturing info into spreadsheet closes this issue.

**Comment by rufuspollock** [comment]
FiXED. See https://ecosystem.lifeitself.org/design
