### ISSUE TITLE
Built-in tool for automatically looking up information on an org (or website)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#76]
When creating a profile for an organization i want to quickly get standard information about the org from their website including a screenshot so that i can jumpstart my profile building process

## Status

Started on this back in Autumn 2021 with https://ecosystem.lifeitself.us/find (code: https://github.com/life-itself/ecosystem/blob/main/pages/find.js). Here's the app in action:

https://user-images.githubusercontent.com/180658/175487163-6a4b7fbc-e24f-40b3-85c7-5fc6efa83351.mov

## Acceptance

* [x] Automatically extract standard metadata from site e.g. title, description
* [x] Generate screenshots
* [x] Display this info available to users
* [ ] Copy-pasteable into relevant other location e.g. spreadsheet if storing info there or yaml frontmatter if using markdown pages

## Tasks

TODO

**Comment by rufuspollock** [comment]
FIXED (or WONTFIX for remaining items for now). this was largely done and i'm not sure how useful per se this is for now. pretty fast to add things by hand. only thing is home page screenshots ... and that is still often by hand.
