### ISSUE TITLE
Contributor workflow for profiles and wiki

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#77]
When wanting to contribute a new profile (especially for first time) I want a clear step by step process to do so so that I can add the profile and have it published

When wanting to update a profile ...

When want to adding a "note" to the wiki (a general page e.g. on related efforts or on integral etc) I want to ...

## Acceptance

* [x] Guide section covering how to contribute to ecosystem wiki site ✅ **[Find here](https://docs.google.com/document/d/1qj6wSq3UCPYMHYXYisKlVfa68DO2n3F1FTjHNcZUkDw/edit#)** 
  * [x] How to add a new page + templates for existing page categories (profiles, topics) ✅
  * [x] How to edit an existing page ✅
* [x] Guide has been checked/tested ✅
* [x] Guide to contributing to ecosystem published on https://ecosystem.lifeitself.us/contribute ✅ Guide can be found [here](https://ecosystem.lifeitself.us/contributors-guide) and is linked to on the [contribute page](https://ecosystem.lifeitself.us/contribute)

## Tasks

- [x] Copy web3 guide content to new doc. ✅ **[Find here](https://docs.google.com/document/d/1qj6wSq3UCPYMHYXYisKlVfa68DO2n3F1FTjHNcZUkDw/edit#)** 
- [x] Write up a guide on how to contribute a profile page ✅
  - [x] Make profile page template incl frontmatter ✅ **[Find here](https://github.com/life-itself/ecosystem/edit/main/profiles-template.md)** 
  - [x] Explain how to fill out frontmatter template ✅
  - [x] Explain how to save logo and images to /img ✅
- [x] Write up a guide on how to add a topics page ✅
  - [x] Make topics page template ✅ **[Find here](https://github.com/life-itself/ecosystem/blob/main/topics-template.md)** 
  - [x] Remove VS Code/Obsidian method and link to web3 guide for those interested
- [x] Guide has been tested ✅ 
  - [x] Any fixes needed done have been done ✅ 
- [x] Guide has been published to site ✅ [Find here](https://ecosystem.lifeitself.us/contributors-guide)
  - [ ] Guide has been given a last look through by a fresh set of eyes 
  - [x] Guide converted into markdown ✅ 
  - [x] Guide has been published ✅ [Find here](https://ecosystem.lifeitself.us/contributors-guide)

**Comment by catherinet1** [comment]
@EilidhRoss1 is taking this one on (thank you!)

Updated job stories and added 1 task to merge #37 here so that could close #37. 

NTS: boot new issue for a 'notes' section where people might add other content (not profiles) ... ?

**Comment by catherinet1** [comment]
@EilidhRoss1 and I had quick call and updated acceptance criteria

**Comment by EilidhRoss1** [comment]
I've formatted the guide into edit a page / add a page. It's much more concise this way, good suggestion @catherinet1. Have removed the code editor/Obsidian info and linked the web3 editors' guide instructions for those wanting to use either of those alternative methods. Next action is for someone to test the guide and make any edits.

**Comment by EilidhRoss1** [comment]
I propose that the next action (to test and edit) go to @theo-cox , and I will look over and publish the essay he was working on. Will confirm with Theo once he's back from leave.

**Comment by theo-cox** [comment]
I have just revuewed @EilidhRoss1 and looks great. My two main bits of feedback:

1) Can we start with a "quickstart" section for people who just want to get stuck in, and then link from this to e.g. background on Markdown? This is probs just moving the actual contributing instructions to the top of the doc. I think it might be a bit off-putting starting with technical stuff, esp. in such a long guide.
2) Will there still be a non-technical way to contribute? I wonder if we risk self-selecting from contributions from certain demographics if the only way to do so is via github, markdown etc

Otherwise I think it looks great and makes sense (although given my familiarity with these tools, I might not be the best test dummy). Overall: safe enough to try, and let's ask for feedback from real users when it's live

**Comment by EilidhRoss1** [comment]
Hi all, after checking the contributors' guide myself on a test account I made, found some issues, which have all been fixed with Khalil's help. 
Thanks for your feedback Theo, I agree that we don't want people to be put off by the technical stuff, however I do think where it is is the best place for it in the document. I have added a sentence in the introduction saying "We have included information on how the site works and its technical architecture. If you’re wanting to get stuck in, feel free to skip over this section and go straight to our instructions on how to edit and add to the site (links to this heading) - you can always refer back if you need to!" I think this should provide a happy medium (technical stuff is still there in a place that makes sense, but option to get stuck in is clear). Re the non-technical way to contribute, my understanding is that that information is already on the site, and the link to this doc will go alongside. 
So next steps, one glance over from a fresh pair of eyes I think would be beneficial, but then I think it's ready to publish! This can then be linked to in your essay @theo-cox

**Comment by rufuspollock** [comment]
@EilidhRoss1 is the guide in markdown? And can we add to the site now - we can do more updating later if needed.

**Comment by EilidhRoss1** [comment]
@rufuspollock not currently in markdown, but can do that

**Comment by EilidhRoss1** [comment]
@rufuspollock just remembered that I thought that the guide was going to be linked to on the site, just like the editors' guide is on the web3 site. If not, I can convert to markdown

**Comment by rufuspollock** [comment]
Yes please markdown and post ...

**Comment by EilidhRoss1** [comment]
contributors' guide is up! https://ecosystem.lifeitself.us/contributors-guide and is linked to on the [contribute page](https://ecosystem.lifeitself.us/contribute)

**Comment by rufuspollock** [comment]
@EilidhRoss1 great - does that mean this issue is done? If so i invite you to have the honor of closing inline with our guidelines https://tao.lifeitself.us/issues/#closing-issues 😄

**Comment by EilidhRoss1** [comment]
FIXED
