### ISSUE TITLE
[epic] Move to markdown wiki model for profile database and content (from spreadsheet)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/ecosystem#78]
Context: we want to make it easier to contribute to the ecosystem project both in terms of profiles as well as general content e.g. notes on thinkers and movements.

To achieve this we want to make the site into more of a markdown (obsidian) wiki - a bit like we have done in web3 project.

The plan is to try using Flowershow so that we get all the functionality that is there e.g. wiki links etc (and start centralizing that!)

This brings us to the question: **How do we integrate flowershow?** Ecosystem is a ood example of a more complex app. Maybe does not integrate nicely 😄

## Acceptance

* [x] Ecosystem site content comes from markdown wiki pages
  * [x] profiles https://ecosystem.lifeitself.us/profiles/life-itself
  * [x] topics https://ecosystem.lifeitself.us/topics/development
  * [x] activitys https://ecosystem.lifeitself.us/activitys/advocacy
* [x] Ecosystem site using flowershow and only has ecosystem specific components (so less to maintain)

Features

* [x] Obsidian links supported **✅2022-09-01 now that we are using flowershow v0.2**
* [ ] FIX: `topic: 0` and similar for activity in data conversion and fix

BONUS - may move to future!

* [ ] Edit this page on relevant pages (?)
* [ ] Landing page: Typing text for name of ecosystem so it can change to different things (so not tied to metamodern)
  * [ ] Revert to "emerging" ecosystem as general reference
* [ ] FUTURE referential integrity for topic and activity references etc

## Tasks

* [x] Design the upgrade @rufuspollock **🚧2022-06-28 in progress. See notes below and tasks**
* [x] Convert data over to markdown (in old ecosystem repo) #79
* [x] #81
  * [x] Refactor lib/db.js to use contentlayer so that search etc keeps working (nothing is using old `data/organization.db` directly, yay!)
* [ ] Other fixes
  * [x] Remove `pages/search.js`
  * [ ] Move `pages/vis2.js` (if wanted) to a markdown page (?)
  * [x] `find.js` ?? **❌2022-09-01 will leave out of this repo for now**
* [x] Releasing the repository: force push over old repo content (assuming we don't just clean) **✅2022-07-05 did this and all working**

```mermaid
graph TD

convert[Convert data over into content folder]
flowershow[Flowershow conversion]
integrate[Integrate content folder - copy it!]

convert --> integrate
flowershow --> integrate
integrate --> push[force push over old repo]
```

### Releasing the repository

Removing sensitive data

* [x] Analyse what sensitive data is there **✅2022-06-27 only thing we can see is some stuff in organization.db e.g. emails**
* [x] organization.db clean up **✅2022-07-08 we decided to just force push a new repo with orgs cleaned up**
  * [x] What are options?
    * filter the organization.db from history - see e.g. https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository
    * reset repo and start clean. Given that we may need this for flowershow upgrade may want to go this root ...
  * live with what's there

**Comment by rufuspollock** [comment]
@khalilcodes what remains here (separate from need to upgrade to latest flowershow soon!)? Are obsidian links supported? What about `topic: 0` item?

**Comment by rufuspollock** [comment]
FIXED. this got done (ages ago e.g. last autumn 2022). May want a quick look at any things to carry over
